///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class R {
  R._();

  // 有关分享的图标
  static const String imagesJoinShare = 'assets/images/icon/icon_share.webp';
}
